name: stated
description: final state
version: 1.0.1
homepage: https://swipelab.co/
repository: https://github.com/swipelab/stated

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
# figure out a way to remove it
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
