name: stated
description: A neat set of tools aimed at making the state management easier.

version: 1.5.0
homepage: https://swipelab.co/
repository: https://github.com/swipelab/stated

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
